### ISSUE TITLE
Transform removing &nbsp;

### ISSUE THREAD

**Issue by jng5** [Mange/roadie#101]
When `transform` is called on a Roadie document, any `&nbsp;` are changed into normal spaces ` `.

I don't think that should be default behavior.

I have edge cases, where an element using for spacing isn't shown if it's empty, so you need something like `<span>&nbsp;</span>`

A better example is images that should not run into each other. Often this is not work:

```html
<img> <img>
```

But this does:

```html
<img>&nbsp;<img>
```

Is this an issue for anyone else?

**Comment by Mange** [comment]
Nokogiri would be the cause of this. Are you sure they are gone, and not
just turned into the actual "non-breaking space" character?

mån 12 jan 2015 20:51 Julie Ng <notifications@github.com> skrev:

**Comment by jng5** [comment]
Yep, they're gone. This is my current workaround:

1. Use regex to catch `&nbsp;`
2. Change them to `%nbspace%`
3. Inline email with roadie
4. Change `%nbspace%` back to `&nbsp;`

This does not affect everyone. Roadie does its job (inlining) fine. I would just consider adding a note to developers about how [nokogiri](https://rubygems.org/gems/nokogiri) may change their markup, in slight ways. That helps when debugging.

Feel free to close this ticket or mark as won't fix.

**Comment by Mange** [comment]
Thank you. I'll leave it open until I add a note about it in the README.
