### ISSUE TITLE
Schemeless URLs should be rewritten

### ISSUE THREAD

**Issue by mjtko** [Mange/roadie#104]
While the changes introduced in 42c382e are great for working with custom schemes and invalid URIs, I'm not convinced of the value of skipping the rewriting of URLs that begin with `//`.

My situation is as follows:

I have an `asset_host` set to a schemeless URI in my app which was working fine in 3.0.0.  After upgrading to 3.0.1 the previously working `image_tag` output (e.g. `//asset.host.com/asset/foo-123456789.png`) no longer works in either Apple Mail (broken image) or GMail (`src` element eliminated as invalid also yielding a broken image).

Is there a reason why this change was made?  It doesn't seem to gel well with HTML email clients unfortunately.  Would you consider backing out this part of that change so schemeless URIs are rewritten again?

**Comment by Mange** [comment]
If it broke for you, then it is a regression and it will be fixed. I
wrongly assumed that email clients would support valid HTML, which of
course is pretty naive.
I'll try to get to this ASAP. Please hardcode the previous version in your
Gemfile until then.

ons 4 mar 2015 11:41 Mark J. Titorenko <notifications@github.com> skrev:

**Comment by mjtko** [comment]
Ok, thanks -- I'll try and find a moment to open a PR unless you beat me to it!

**Comment by Mange** [comment]
I just released version 3.0.4 with a fix included. Thank you for reporting. :+1:
