### ISSUE TITLE
Warn in Roadie::Inliner elements_matching_selector

### ISSUE THREAD

**Issue by seattlecyclist** [Mange/roadie#105]
Hi,

We are seeing Roadie warn us it cannot use a selector.  This is a mild irritant in testing as our test output gets flooded with Roadie warnings.  I have spent some time debugging it and  found that we are getting a Nokogiri error `Invalid expression: //﻿[contains(concat(' ', normalize-space(@class), ' '), ' column ') and contains(concat(' ', normalize-space(@class), ' '), ' scrollable ')]`  THis is around line 70... in the rescue block.

I have also done some debugging of the selector variable and found something interesting.  If I debug via Pry  I can see the following:
```
0> selector.to_s
=> "﻿.column.scrollable"

0> ".column.scrollable".bytes.to_a
=> [46, 99, 111, 108, 117, 109, 110, 46, 115, 99, 114, 111, 108, 108, 97, 98, 108, 101]
```

BUT....... 

```
0> selector.to_s.bytes.to_a
=> [239, 187, 191, 46, 99, 111, 108, 117, 109, 110, 46, 115, 99, 114, 111, 108, 108, 97, 98, 108, 101]
```

NOTE:  the selctor.to_s_bytes does not match what the raw string byte output is.  

Furthermore:
```
0> dom.css(".column.scrollable")
=> []
```
WORKS
while:
```
0> dom.css(selector.to_s)
=> Invalid expression: //﻿[contains(concat(' ', normalize-space(@class), ' '), ' column ') and contains(concat(' ', normalize-space(@class), ' '), ' scrollable ')]
```

Generates the nokogiri error.

I should also say that we are are using Sass w/ asset pipelines on Rails 4.1.9 and on ruby 2.1.2

Like I said, this is mostly an annoyance in our tests, but I would like to get it fixed.

Thanks in advance.

**Comment by Mange** [comment]
Hi,

Looks like you have three bytes extra in the beginning: `239`, `187`, `191`.

I looked in `irb` to see what they could be:
```
2.1.1 :001 > a = [239, 187, 191]
 => [239, 187, 191] 
2.1.1 :002 > a.pack("c*")
 => "\xEF\xBB\xBF" 
```

I recognized it, but wasn't sure. When I typed `0xef 0xb` it autocompleted to `0xef 0xbb 0xbf` and lead to my guess. It's the [Byte Order Mark](http://en.wikipedia.org/wiki/Byte_order_mark).
I don't know which part of the stack should have handled this (stdlib, or CSS Parser gem), but you can fix it by stripping the first three bytes from your stylesheet file, or adding an extra empty line at the start of the file. I presume the ".column.scrollable" is the first style in the file?

```css
.column.scrollable { ... }
```

Can be changed to:

```css

.column.scrollable { ... }
```

Let me know how this works out for you.

**Comment by seattlecyclist** [comment]
Hey Great idea! We tried that, but our files are generated by by haml(as we are using .sass) and do not have that in them.  We ran dos2unix on the actually generated .sass files and they did not contain anything like that.

**Comment by Mange** [comment]
Open the Sass file in a hex editor and confirm that no BOM is there. Next
step would be to find out if sass adds it when generating.

It should still work with a comment on top of the file, as long as you do a
comment that stays in the generated file (a multi-line comment should pass
right through).

fre 24 apr 2015 22:15 Mike Porter <notifications@github.com> skrev:

**Comment by seattlecyclist** [comment]
Mange and everybody,

We found a fix here:
https://github.com/sass/sass/issues/1395

We had unicode characters in a content style for quotes. Replacing the unicode with the equivalent escaped sequence worked.

Thank you for all your help!

**Comment by Mange** [comment]
Thank you for keeping us posted! I'm happy you solved it.
