### ISSUE TITLE
Roadie doesn't encode special characters

### ISSUE THREAD

**Issue by jakebolam** [Mange/roadie#109]
Roadie does not encode special characters.

Having &copy; in an email saved in utf-8 will result in no output. Other extended characters do nto render correctly either.

Looks like Nokogiri punts and defaults to ASCII-8bit, which results in the multibyte characters being mangled. We need to have the option of specifying the file type and passing it through to Nokogiri before the parse.

**Comment by jakebolam** [comment]
FIXED:
This issue was not to do with roadie, but the way I was reading in the HTML

original I was doing:
```
html = File.open(path, "r").read
```

I've now changed it to force the encoding, which fixed the problem
```
html = File.open(path, "r:UTF-8").read
```

**Comment by Mange** [comment]
Great. I'm glad you were able to fix it.

fre 4 sep 2015 05:23 Jake Bolam <notifications@github.com> skrev:
