### ISSUE TITLE
NameError: uninitialized constant Roadie::NetHttpProvider

### ISSUE THREAD

**Issue by xavierperera** [Mange/roadie#110]
Hi there!
 I can use the other providers but I have problems with Roadie::NetHttpProvider, was it removed from Roadie? http://www.rubydoc.info/github/Mange/roadie/index

**Comment by Mange** [comment]
You need to use the latest prerelease to get it.

ons 30 sep 2015 03:25 Xavier <notifications@github.com> skrev:

**Comment by Mange** [comment]
I just released 3.1.0 now, so you no longer need to use a pre-release. :-)
