### ISSUE TITLE
How to remove styles in the head tag of email?

### ISSUE THREAD

**Issue by PikachuEXE** [Mange/roadie#112]
I found this when inspecting the source of HTML emails
I am trying to avoid HTML emails being cropped off by GMail (and possibility other email clients)
```html
<head>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type">

<style>
.selector:visited{text-decoration:none}
.selector:hover{text-decoration:none}
.selector:focus{text-decoration:none}
.selector:active{text-decoration:none}
(Many more useless style rules...)
</style>
```

**Comment by Mange** [comment]
Check the README. There's a configuration option to disable keeping
uninlinable styles in the head.

You could also use a simpler stylesheet for your emails that doesn't have
as many rules in them.

tis 24 nov. 2015 03:52 PikachuEXE <notifications@github.com> skrev:

**Comment by PikachuEXE** [comment]
Sorry for not reading the README first :sweat_smile:
