### ISSUE TITLE
CSS parsing bug - confused by whitespace in nth-child

### ISSUE THREAD

**Issue by khiner** [Mange/roadie#118]
```
Roadie: Got error when looking for ".vz-Viz-gridBg rect:nth-child(4n + 3)" (from "//redacted.css" stylesheet): expected an+b node to have either + or - as the operator, but is " + "
ArgumentError: expected an+b node to have either + or - as the operator, but is " + "
```

**Comment by Mange** [comment]
This is a nokogiri problem. Roadie is just reporting Nokogiri errors.

Does the CSS spec allow spaces there?

tors 28 jan. 2016 22:59 Karl Hiner <notifications@github.com> skrev:

**Comment by Mange** [comment]
I checked it out. [CSS spec *does* allow spaces there](https://www.w3.org/TR/css3-selectors/#nth-child-pseudo). Clearly a bug in Nokogiri.
