### ISSUE TITLE
CSS rules are not merged for an element

### ISSUE THREAD

**Issue by carsonreinke** [Mange/roadie#119]
```ruby
html = <<-HTML
<html>
<head>
  <style>
  p {
    font-size: 10px;
  }
  p.big {
    font-size: 20px;
  }
  </style>
</head>
<body><p class="big"></p></body>
</html>
HTML

document = Roadie::Document.new html
document.transform
```
will produce: `<p class="big" style="font-size:10px;font-size:20px"></p>`

Obviously, the later rule should override the first.  Using `CssParser::RuleSet#expand_shorthand!` and some sort of hash to merge the rules together might work.  I guess the only problem though, is expanded shorthand is not always the [best](http://chipcullen.com/html-email-and-borders/).

**Comment by carsonreinke** [comment]
Oh, looks like the `RuleSet` just needs to be merged together:

```ruby
$> rule_set = CssParser::RuleSet.new(nil, 'font-size: 10px; font-size: 20px;')
$> rule_set.to_s()
 => "{ font-size: 20px; }"
```

**Comment by Mange** [comment]
This is intentional. What if you specified "color: #eee; color:
rgba(255,255,255,0.8)"?

CSS progressive enhancement works by ignoring values the client does not
understand.

tis 2 feb. 2016 19:06 Carson Reinke <notifications@github.com> skrev:

**Comment by carsonreinke** [comment]
I can see your point with that, however, premailer does what I would expect:

```
$> echo "<html>
> <head>
>   <style>
>   p {
>     font-size: 10px;
>   }
>   p.big {
>     font-size: 20px;
>   }
>   </style>
> </head>
> <body><p class="big"></p></body>
> </html>" | premailer
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>
  
</head>
<body><p class="big" style="font-size: 20px"></p></body>
</html>
```

It is common to override a style without trying to do a progressive enhancement.

**Comment by Mange** [comment]
Yes, but it's not possible to determine which one the developer intends to
do. I optimize for less surprise and a behavior as close as a browser that
is possible.

It's possible to create a stylesheet that does not override if the email
size is very important when this is the method used, but it's not possible
to progressively enhance with the other method. I have to choose the one
that gives more flexibility.

You can also use your own transformation function to handle this if you
don't want to refactor your stylesheet (for example by placing the base
font size on "body", or by having a class "small" and require one of them
in the markup[1]). You could iterate all nodes with a "style" attribute,
parse it and deduplicate the properties and write them back.

[1]: I realize that this was a minimal example, so see my example as the
same. I know your situation is probably a lot more complex.

tors 4 feb. 2016 22:58 Carson Reinke <notifications@github.com> skrev:

**Comment by carsonreinke** [comment]
Progressive enhancement might be better kept to using media queries and non-inline (its suppose to be for a modern email client right?).

You might want to consider an option to have these styles normalized.  Also, it would be wise to note the default does not do this.

Also, here are some other CSS inliners that work as would expect them:
- MailChimp: http://templates.mailchimp.com/resources/inline-css/
- Campaign Monitor: https://inliner.cm/
- Litmus: https://putsmail.com/inliner

I'd be happy to do a PR if interested.

**Comment by carsonreinke** [comment]
Ran a test with the following on Email On Acid:

```html
  <p class="small" style="font-size:10px;">My Test</p>
  <p class="multiple" style="font-size:10px;font-size:40px;">My Test</p>
  <p class="big" style="font-size:40px;">My Test</p>
```

Every email client respected the later style.  So, it seems like this really is a non-issue.

Is there any guarantee of style ordering?  That is, will all the overriding be guaranteed to come in the order defined?

**Comment by Mange** [comment]
> Progressive enhancement might be better kept to using media queries and non-inline (its suppose to be for a modern email client right?).

Most email clients do not understand media queries, and the most common HTML rendering engine in HTML emails is Microsoft Word. Modern email clients are like the web was 10 years ago.

> You might want to consider an option to have these styles normalized.

I have considered it, and I didn't want to include one as it would complicate things things. (Of course I'm not dogmatic about it, if more people have a need for it, I'll reconsider.)

> Also, it would be wise to note the default does not do this.

Yes, it would actually be wise. I will make it so.

> Also, here are some other CSS inliners that work as would expect them.

That means, to me, that Roadie have a feature they don't. Roadie support the use of RGBA colors in emails with a nice fallback, while they don't. Roadie support gradient backgrounds with a simple fallback, but they don't.

> Every email client respected the later style. So, it seems like this really is a non-issue.

That's expected in your example as that's how CSS works. You should try this one:

Place a box within a box. Make the outside box have an background image. The inner box should have a semi-transparent background, with a fallback color if the client does not support RGBA.

```css
.outer {
  background: url(/some/image.jpg);
  padding: 1em;
}
.inner {
  background: #eee;
  background: rgba(255, 255, 255, 0.5);
}
```

Inline the styles, and if you don't support progressive enhancement you get unreadable text on a client that does not support RGBA. You get a proper fallback to `#eee` if you don't remove this information from the email.

> Is there any guarantee of style ordering? That is, will all the overriding be guaranteed to come in the order defined?

Yes. There are several tests making sure of this. We even clean up some statements that are guaranteed to be redundant, like this situation:

```css
font-size: 20px; font-size: 40px; font-size: 20px
```

This will be cleaned up to just

```css
font-size: 40px; font-size: 20px
```

as the first and last values are the same. This works for any number of entries; two exact same `property: value` will be deduplicated.

```css
font-size: 20px; font-size: 40px; font-size: 20px; font-size: 20px; font-size: 40px; font-size: 20px; font-size: 40px; font-size: 20px; font-size: 40px
```

will end up as

```css
font-size: 20px; font-size: 40px
```

---

I hope I managed to explain this feature well enough. I also hope I don't sound harsh. Again, I cen help you write a workaround for your case. It'll look something like this:

```ruby
class StyleMinimizer
  def call(dom, *)
    dom.css("*[style]").each do |node|
      node["style"] = minimize_style(node["style"])
    end
  end

  private
  def minimize_style(style)
    return style if style.nil? || style.empty?
    seen = Set.new
    style.split(";").reverse.select { |rule|
      property, _ = rule.split(":", 2)
      if seen.include?(property)
        false
      else
        seen << property
        true
      end
    }.reverse.join(";")
  end
end

document.after_transformation = StyleMinimizer.new
```

I just typed this out in this comment. It probably doesn't work, but a few tests for the behavior should be all you need to refactor this until it looks acceptable and verify that you get the behavior you want out of it.

**Comment by carsonreinke** [comment]
I guess what I am saying is if you are trying to do something more advanced with say CSS3, media queries [probably might work](https://www.campaignmonitor.com/dev-resources/guides/mobile/).

While I understand your point about the progressive enhancement, the more common use case is not to do that (as several inliners work as I would expect them).  There is also some situations that combining short-hand and long-hand together, clients become thoroughly confused.  For example, mixture of `padding: 0;` and `padding-top: 0` and such.  Since the email clients are not always the most dependable for rendering, I think it is best to just simplify the interpretation for them.

Thank you for the `after_transformation` example, though I was thinking possible a specific feature of this gem could support either mode.  If I get motivated, I will put in a PR.
