### ISSUE TITLE
undefined method `children' for nil:NilClass

### ISSUE THREAD

**Issue by asecondwill** [Mange/roadie#126]
I have a notification email in my app, sometimes but not always, I get the error

````
undefined method `children' for nil:NilClass
````

The application stack trace ends at:

```` BidMailer.notification(@bid).deliver_now ````

and the stack trace ends at:

```` File "/var/deploy/flexpertlinode/web_head/shared/bundle/ruby/2.2.0/gems/roadie-3.1.1/lib/roadie/markup_improver.rb" line 61 in create_head_element
 ````

Is this likely to be a roadie issue?  Or something i need to look out for in the email template? 

my set up:
gem 'roadie-rails', '~> 1.0'
gem 'rails', '4.2.4'

**Comment by Mange** [comment]
Sounds like Roadie is to blame.
Could you provide more information? Is your HTML unparseable in certain
cases, perhaps? Like an unclosed element or something major in the
beginning of the email?

Den tis 24 maj 2016 13:19will <notifications@github.com> skrev:

**Comment by asecondwill** [comment]
Hi

I get the error every time for some records, but not for others. I use the same template for every email in the app, only this mailer has problems.   It's not dependent on recipient email.  I stripped the template down to:

```
<h5>New Job Application</h5>

<p>
  You have a new application.
</p>

```

So no tag errors there.  

The layout is from Zurb's ink project:



```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width"/>
  <%= stylesheet_link_tag "mailer" %>
  <style>
/**********************************************
* Ink v1.0.5 - Copyright 2013 ZURB Inc        *
**********************************************/
/* mods */
.header{background-color: #f8f8f8; border-bottom: 1px solid #b5b5b5}
  </style>
</head>
<body>
  <table class="body">
    <tr>
      <td class="center" align="center" valign="top">
        <center>
          <table class="row header">
            <tr>
              <td class="center" align="center">
                <center>
                  <table class="container">
                    <tr>
                      <td class="wrapper last">

                        <table class="twelve columns">
                          <tr>
                            <td class="six sub-columns">
                              <img src="http://example.com.au/example/emails/img/email-logo.gif">
                            </td>
                            <td class="six sub-columns last" style="text-align:right; vertical-align:middle;">
                              <span class="template-label">example.com.au</span>
                            </td>
                            <td class="expander"></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </center>
              </td>
            </tr>
          </table>

          <table class="container">
            <tr>
              <td>
                <table class="row">
                  <tr>
                    <td class="wrapper last">

                      <table class="twelve columns">
                        <tr>
                          <td>
                            <br><br>
                            <%= yield %>
                          </td>
                          <td class="expander"></td>
                        </tr>
                      </table>

                    </td>
                  </tr>
                </table>
                <table class="row callout">
                  <tr>
                    <td class="wrapper last">
                      <table class="twelve columns">
                        <tr>
                          <td><hr></td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
                <table class="row">
                  <tr>
                    <td class="wrapper last">
                      <table class="twelve columns">
                        <tr>
                          <td align="center">
                            <center>
                              <p style="text-align:center;"><a href="http://example.com.au/pages/terms-of-use">Terms</a> | <a href="http://example.com.au/pages/privacy-policy">Privacy</a> | <a href="http://www.example.com.au/settings">Preferences</a></p>
                            </center>
                          </td>
                          <td class="expander"></td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              <!-- container end below -->
              </td>
            </tr>
          </table>
        </center>
      </td>
    </tr>
  </table>
</body>
</html>
```

**Comment by asecondwill** [comment]
Any feedback here? it's bit of a (sorry) roadblock for me.

**Comment by Mange** [comment]
I have no idea what could be wrong here. I see nothing dynamic in HTML, so
I cannot explain what could be wrong here. Maybe it's something with your
version of Nokogiri?

Try changing the template to HTML instead of XHTML and see what happens.

Den fre 27 maj 2016 08:07will <notifications@github.com> skrev:

**Comment by asecondwill** [comment]
One part of the problem is it's just crashing out with no useful info about why.  it does seem really really odd though.

**Comment by asecondwill** [comment]
i'm on gem 'nokogiri', '~> 1.6.7.2'

**Comment by asecondwill** [comment]
using pry in the gem code locally shows that Document initializer is being passed "" as the original html.

**Comment by asecondwill** [comment]
I've changed the html to just <html> with no doctype declared. sill not working

**Comment by mikecarroll** [comment]
Also encountering this issue.

**Comment by Mange** [comment]
Please re-open this issue to `roadie-rails` instead.

* Does it work when you write a test that inlines the markup? E.g. does this only happen in `production`, or also in `test`/`development`?
* Does *any* mail work? Is it just this markup? Can you create a minimal case that causes the problem?
* Are you using `Automatic` or `Mailer`? If using `Automatic`, please use `Mailer` instead since it's a lot more stable and easier to get working.

**Comment by Deuteu** [comment]
I have the same issue using directly `roadie` gem and not `roadie-rails` gem.

**Comment by adamkiczula** [comment]
I ran into a similar issue, it turned out that I was sending in a `ActionMailer::Base::NullMail` object in some cases, which would then cause the Roadie internals to fail to find an html element to attach the head element to.

**Comment by Mange** [comment]
> I ran into a similar issue, it turned out that I was sending in a `ActionMailer::Base::NullMail` object in some cases, which would then cause the Roadie internals to fail to find an html element to attach the head element to.

Interesting! If you can figure out a good way to handle this, PRs are very welcome.

If others report it here, then we could also just add it to the FAQ as a possible cause for this problem.
