### ISSUE TITLE
Support css_parser 1.4.x

### ISSUE THREAD

**Issue by domcleal** [Mange/roadie#127]
The gemspec is currently locked to css_parser 1.3.x, but this could be loosened to include 1.4.x or even all 1.x greater than 1.3.4.

**Comment by Mange** [comment]
I've opened up an issue with `css_parser` gem here: premailer/css_parser#76

Until I have an answer I'll make it compatible with 1.4.x only.

**Comment by Mange** [comment]
Version 3.2.0 was just released with this fixed. Thank you for your report! :heart:
