### ISSUE TITLE
Support Outlook's approach to margins

### ISSUE THREAD

**Issue by tbrammar** [Mange/roadie#129]
Outlook doesn't support the inline `margin` tag and all its descendants. Until recently it was thought Microsoft had removed support for this tag, but it actually transpires it is still supported as long as the first letter is capitalised. E.g.

```
margin
margin-top
margin-right
margin-bottom
margin-left
```
becomes
```
Margin
Margin-top
Margin-right
Margin-bottom
Margin-left
```
More details can be found here: https://www.emailonacid.com/blog/article/email-development/outlook.com-does-support-margins

I know that we can supply this capitalised tag inline and that Roadie won't overwrite, but is there anyway that this inflection could be supported in the gem?

**Comment by Mange** [comment]
Well, I think it makes sense. The CSS is still valid everywhere else AFAIK
and it is just one way we need to transform our CSS to support email
clients.

I can't promise that I get to this soon, but a PR would be welcome if
someone feel that they have time. :-)

Den mån 21 nov. 2016 18:06Tom Brammar <notifications@github.com> skrev:

**Comment by Mange** [comment]
I will not implement this, but I could be willing to give a PR a look if it ever appeared.

Things I'd look for in this PR:

- I'd like this behind a toggle, that is default off. It could be named something like `document.rewrite_css_for_outlook_compatibility = true` or something like that.
- Multiple tests for the behavior (that only some styles are rewritten).
- A reference link where you can read about it.
- A section in the README explaining this.

I hope this list makes it clearer how I feel about it, so as to not waste any future contributor's time waiting for a review. It's not to be bossy! :smile:
