### ISSUE TITLE
New release supporting Nokogiri 1.7?

### ISSUE THREAD

**Issue by mrcasals** [Mange/roadie#134]
Hi!

I'm using roadie on our project https://github.com/AjuntamentdeBarcelona/decidim, I'm currently trying to update it to Ruby 2.4. It seems that roadie already supports nokogiri 1.7, but there's no release for it. Can you release a new version of the gem supporting it?

Thanks!

(Note: I could not find a way to contact you directly through Twitter, so I decided to open this as an issue, sorry about that!)

**Comment by Mange** [comment]
I've just released version 3.2.1 with this fix included. I apologize for the delay.

**Comment by mrcasals** [comment]
Awesome, thank you for your time supporting this project! :)
