### ISSUE TITLE
Weird issue with content: '•'; in my CSS

### ISSUE THREAD

**Issue by rsl** [Mange/roadie#135]
i've had to add this to handle some inline bullets and getting this error from Roadie:

Roadie: Cannot inline "﻿table.index" from "/Users/rsl/Dev/sheets/app/assets/stylesheets/brands/default_mail.scss (live compiled)" stylesheet. If this is valid CSS, please report a bug.

if i comment out the content call, it's fine so it seems to be that. any ideas? thanks.

**Comment by rsl** [comment]
hrm... this could be a unicode issue? if i change the bullet to plain ascii, everything seems ok.

**Comment by rsl** [comment]
it was unicode issue. able to use "\nnnn" notation to get around it. [underlying nokogiri issue not roadie]

**Comment by Mange** [comment]
Good debugging effort. Thanks!

Den ons 15 feb. 2017 15:40Russell Norris <notifications@github.com> skrev:

**Comment by rsl** [comment]
heh too bad i didn't do it right before filing ticket, eh? hehehe
