### ISSUE TITLE
Convert rem to px?

### ISSUE THREAD

**Issue by glebm** [Mange/roadie#136]
Is there a way to tell Roadie to convert all `rem` to `px` at e.g. 16px per rm, to avoid issues when the email client root font size is not 16px?

Apologies if this has already been discussed.

**Comment by Mange** [comment]
No, there is no support for this and it is not on the roadmap.

I think you need to manually stick to `px` for your email CSS, or use a compile-to-CSS system where you can transform this yourself before sending it off to Roadie.
