### ISSUE TITLE
Allow anchor tags to be ignored

### ISSUE THREAD

**Issue by hasghari** [Mange/roadie#137]
There is already support for ignoring `style` tags by using `data-roadie-ignore`. It would be nice if we could do the same for `a[href]` tags as well. My use case is using a placeholder url for mailgun like so:

```html
<a href="%tag_unsubscribe_url%"></a>
```

Currently this fails because `URI.parse` throws an exception.

**Comment by Mange** [comment]
This makes a lot of sense. I'd love to see a PR for it! :+1:

**Comment by Mange** [comment]
Fixed in #154.

**Comment by Mange** [comment]
Version 3.3.0 was just released with this included.
