### ISSUE TITLE
nokogiri is locked to 1.7.x, 1.8.x is out.

### ISSUE THREAD

**Issue by bbenezech** [Mange/roadie#140]
Is there a good reason to lock the minor bit instead of the major one? Did the maintainers break Semver in the past?

**Comment by Mange** [comment]
I can not remember. If they are committed to semver I'm all for unlocking the version, no matter past transgressions if any. ☺️

**Comment by tom-lord** [comment]
I did a little digging, at it *appears* this version lock is a remnant of (now-dropped) [support for ruby 1.8.7](https://github.com/Mange/roadie/commit/1c4a49a417daf30a1db2a1714ab26c3571b97b8a#diff-2e17a7a89dd86c254df8df64139c2269).

The current restriction is:

    s.add_dependency 'nokogiri', '>= 1.5.0', '< 1.8.0'

`1.5.x` is (according to the commit history) only supported for ruby versions < 2.2, and I cannot see a reason for the `< 1.8.0` lock. I think this could be changed to `~> 1.5`.

**Comment by tom-lord** [comment]
...And on that note, if the gem supports ruby version `1.9.3` then it would be a good idea to [add this to the travis configuration](https://github.com/Mange/roadie/blob/master/.travis.yml). Currently, only versions `>=2.1` are being tested.

**Comment by Mange** [comment]
We dropped support for non-supported versions of Ruby just a few weeks ago. Thank you for digging that out. 

It should definitely be changed.

**Comment by Mange** [comment]
I just released version 3.2.2 with a fix for this included. Thank you for your help! :heart:
