### ISSUE TITLE
Stylesheet BOM stripping doesn't work with NetHttpProvider

### ISSUE THREAD

**Issue by larryfox** [Mange/roadie#145]
Hi, we recently discovered a bug from the change added in f21c8384092ded4b9c9361265798469d14cf0d44.

The `NetHttpProvider` uses `Net::HTTP` under the hood which returns a [response body encoded as `ASCII-8BIT`](https://bugs.ruby-lang.org/issues/2567). 
This leads to an `Encoding::CompatibilityError`, when the `Stylesheet` initializer does the BOM substitution: `css.sub(BOM, "")` 

The following code demonstrates the issue:

```ruby
BOM = "\xEF\xBB\xBF".force_encoding('UTF-8').freeze
r = Net::HTTP.get_response(URI('http://example.com/some.css'))
r.body.sub(BOM, '')
# Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8
```

One solution (which we monkey patched ourself) would be changing [this line](https://github.com/Mange/roadie/blob/23cdec197f5034833725569449f0addb53650077/lib/roadie/net_http_provider.rb#L37) to:

```ruby
Stylesheet.new url, response.body.force_encoding('UTF-8')
```

But I'm unsure if this will introduce other issues or not.

**Comment by Mange** [comment]
That's strange. Isn't the server giving an encoding in the headers? I
thought Net/HTTP marked the stream according the the encoding specified in
the server.

Forcing to UTF-8 is suboptimal for users not using UTF-8, which is pretty
common in the east and legacy systems in the west. I have no idea about
Africa or other parts of the world.

What is the contents of the Content-Type header? ☺️

Den fre 30 juni 2017 17:20Larry Fox <notifications@github.com> skrev:

**Comment by larryfox** [comment]
That was our first thought too, but we set our headers to `text/css; charset=UTF-8` explicitly. 

Unfortunately, `net/http` doesn't do anything with the Content-Type headers, see the discussion here https://bugs.ruby-lang.org/issues/2567

If forcing utf-8 is suboptimal another solution would be to trust the Content-Type charset if it's given, something like:

```ruby
body = if charset = response.type_params['charset']
  response.body.force_encoding(charset)
else
  response.body
end

Stylesheet.new(url, body)
```

**Comment by Mange** [comment]
Yes, that approach looks really good! PRs welcome, or I'll get to it sometime this year.

**Comment by jufemaiz** [comment]
We've just hit this too :(

Was there any movement?

**Comment by Mange** [comment]
Sorry, no. But I've since written net/http code in other projects where I hit the problem that the body is always returned as an byte string.

I know the proposed solution above works. A PR would be welcome.

**Comment by jufemaiz** [comment]
@Mange no problems, understand! One of my team has had a crack at it. Please see @jeznag's work 👍

**Comment by Mange** [comment]
Since #152 and #153 this is now fixed in `master`. Let me know if it works for you now. :-)

**Comment by Mange** [comment]
Version 3.3.0 was just released with this included.
