### ISSUE TITLE
support anchor/ image url stripping inside conditional tags

### ISSUE THREAD

**Issue by fran-worley** [Mange/roadie#148]
When adding images or anchor tags inside conditionals:

```
<!--[if gte mso 9]>

<![endif]-->
```

The urls in images and anchor tags don't seem to be transformed.

**Comment by Mange** [comment]
That is by design. Everything inside there is inside a comment and so will
not be available in the DOM.

You will have to generate full URLs from the start if you want absolute
URLs inside HTML comments.

**Comment by fran-worley** [comment]
See that's the thing, it's not a comment to outlook or whatever you're targeting with the conditional.

Is there not a way of distinguishing between a regular comment and a conditional?

Sent from my iPhone

On 27 Sep 2017, at 19:01, Magnus Bergmark <notifications@github.com<mailto:notifications@github.com>> wrote:

That is by design. Everything inside there is inside a comment and so will
not be available in the DOM.

You will have to generate full URLs from the start if you want absolute
URLs inside HTML comments.

**Comment by Mange** [comment]
Sorry, but that's just a thing Outlook does. It is a real comment to every
conforming HTML parser out there.

Is there a reason why it would be hard to generate full URLs inside the
comment when you generate it originally?

If so, your only option is to replace them using normal string methods
before passing it to Roadie. But that's also what Roadie would do if it had
to support this.

**Comment by fran-worley** [comment]
In my example I had an image link to replace a css styled link in outlook as I couldn't get reliable support for background colours and border radiuses.

I ended up scrapping the conditional entirely and going with the image link which was less than ideal as I had wanted the image button to be a compatibility measure.

I completely get what you're saying but to outlook the inside of those comments is the DOM so I was a little surprised when urls weren't transformed.

Sent from my iPhone

On 27 Sep 2017, at 19:16, Magnus Bergmark <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry, but that's just a thing Outlook does. It is a real comment to every
conforming HTML parser out there.

Is there a reason why it would be hard to generate full URLs inside the
comment when you generate it originally?

If so, your only option is to replace them using normal string methods
before passing it to Roadie. But that's also what Roadie would do if it had
to support this.

**Comment by Mange** [comment]
Yeah, when it comes to email clients you usually just have to give up being a web developer and just go back to tables for layout and images for gradients and buttons. 🙃

I'm glad you got a working workaround.
