### ISSUE TITLE
Image style attributes - Outlook (on windows) special cases

### ISSUE THREAD

**Issue by fran-worley** [Mange/roadie#149]
Outlook ignores pretty much all styling on images in favour of html attributes. 

You could argue that we should be ensuring that our images are exactly the right size, and have the necessary whitespace but our email writers are not image manipulation proficient and prefer to use the tools in our online editor. 
For now we get reasonable results by adding these html attributes as-well-as the inline css for image tags.

html attr | css style
---------|----------
`align` | `float`
`width` | `width`
`height` | `height`  
`vspace` |  Any of: `margin-top` `margin-bottom` `padding-top` `padding-bottom`
`hspace` | Any of: `margin-left` `margin-right` `padding-left` `padding-right`

Is this something you might consider handling automatically or if not could you point me in the direction of how I might handle this as part of Roadie transform?

**Comment by Mange** [comment]
I think it would be hard to handle automatically for everyone sadly, but it's a good case for a "plugin" someone could ship. 😀

It should be possible to implement using transformation blocks. In there you could search for elements in the document matching `img[style]` and then parse the style text and apply changes to the node.

The css_parser gem, used by roadie, could potentially help with this. It has support for expanding some properties to normalize them (ex. expanding "margin" to "margin-top", etc.) which should help here.
