### ISSUE TITLE
How to use asset pipeline with data-immutable?

### ISSUE THREAD

**Issue by d13r** [Mange/roadie#27]
First, thanks for this gem, it's great for sending HTML emails that have to work in Gmail!

I was just wondering what's the best way to use the asset pipeline to create the CSS for responsive design, but then have it converted to a `<style>` tag when sending?

For example, I'd like to have something like this:

```
<link rel="stylesheet" type="text/css" href="email-common.css">
<link rel="stylesheet" type="text/css" href="email-responsive.css" data-immutable>
```

And have the first one inlined (which it is), but have the second one converted to a `<style>` block, so there's no external stylesheets to be loaded by the email client.

This is the best I've come up with, which is specific to the asset pipeline and won't work with the filesystem option. I don't yet know if it will even work in production!

```
<style type="text/css" data-immutable>
<%= Rails.application.assets['email-responsive.css'].to_s.strip %>
</style>
```

As far as I can see, Roadie can't do this automatically. Would you consider adding that as an option - e.g. another 'data-' parameter? If not, perhaps you could add something about it to the readme?

Thanks
Dave

**Comment by avand** [comment]
I think you mean `style` where you say `span`. Just FYI.

**Comment by Mange** [comment]
Oh, yes. Talk about typo.
