### ISSUE TITLE
Support URLs with Mandrill *|MERGE VARS|*

### ISSUE THREAD

**Issue by dblandin** [Mange/roadie#91]
I'm currently getting the following error when roadie tries to process a template with a [Mandrill merge var](http://help.mandrill.com/entries/21678522-How-do-I-use-merge-tags-to-add-dynamic-content-):

```
Roadie::InvalidUrlPath: Cannot use path "https://domain.com/path?token=*|token|*" in URL generation. Caused by: bad URI(is not URI?): https://domain.com/path?token=*|token|*
        from /var/www/app/shared/bundle/ruby/2.1.0/gems/roadie-3.0.0/lib/roadie/url_generator.rb:114:in `rescue in parse_path'
        from /var/www/app/shared/bundle/ruby/2.1.0/gems/roadie-3.0.0/lib/roadie/url_generator.rb:112:in `parse_path'
        from /var/www/app/shared/bundle/ruby/2.1.0/gems/roadie-3.0.0/lib/roadie/url_generator.rb:108:in `path_is_absolute?'
        from /var/www/app/shared/bundle/ruby/2.1.0/gems/roadie-3.0.0/lib/roadie/url_generator.rb:58:in `generate_url'
        from /var/www/app/shared/bundle/ruby/2.1.0/gems/roadie-3.0.0/lib/roadie/url_rewriter.rb:47:in `generate_url'
        from /var/www/app/shared/bundle/ruby/2.1.0/gems/roadie-3.0.0/lib/roadie/url_rewriter.rb:71:in `transform_element'
        from /var/www/app/shared/bundle/ruby/2.1.0/gems/roadie-3.0.0/lib/roadie/url_rewriter.rb:25:in `block in transform_dom'
```

URI, which roadie's URLGenerator is using, doesn't seem to like this type of URL:

``` ruby
>> URI("https://domain.com/path?token=*|token|*")
=> URI::InvalidURIError: bad URI(is not URI?): https://domain.com/path?token=*|token|*
```

Any thoughts on how to resolve this issue? It's preventing us from upgrading to 3.0.

**Comment by nim1989** [comment]
`method(:inline_mandrill))` instead of `  method(&:inline_mandrill))`. ;)

**Comment by Mange** [comment]
;-)

tis 28 apr 2015 17:49 Nima Izadi <notifications@github.com> skrev:

**Comment by gjastrab** [comment]
If we wanted to do something like this is there a way to configure it via an initializer or is overriding `roadie_options` in the mailer the only way? (need to do something similar for sendgrid's unsubscribe tag)

**Comment by Mange** [comment]
The initializer takes the same options as the roadie_options in the
mailers. It's up to you where you want to configure it.

Den mån 11 juli 2016 22:27Greg Jastrab <notifications@github.com> skrev:

**Comment by gjastrab** [comment]
In your example code above that looks like you're overriding `roadie_options` within the mailer. I was unsure how to do that in the initializer, but then realized that was the top method in your example to just set the after_transformation, so in an initializer it would be like:

```
config.roadie.after_transformation = ->(doc) {
  doc.css('[data-sendgrid-href]').each do |elem|
    elem['href'] = elem.delete 'data-sendgrid-href'
  end
}
```

instead of operating on document. Thanks!

**Comment by ArtisanalPickle** [comment]
@Mange thanks for all the help here. I got my configuration working on this for the most part, but am having trouble getting the merge tags to transfer to the `href` properly; instead, some part of the process is HTML escaping the merge tags, so my link output ends up looking something like this:

```
<a href="*%7Csome_url%7C*">Click here</a>
```

Not sure if this is Nokogiri doing this or what, but wondering if you have some insight, thanks!
